name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    name: Build @${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -t hustcer/react-native .
          docker run --rm --name rn-env hustcer/react-native /bin/sh -c "npx envinfo"
      - name: Checkout React Native
        run: git clone https://github.com/facebook/react-native.git
      - name: Build React Native
        run: |
          docker run --rm --ulimit nofile=10240 -v "$(pwd)/scripts/":/scripts -v "$(pwd)/react-native/":/react-native -w /react-native hustcer/react-native /bin/sh -c "/scripts/test-react-native-setup.sh"
